version: 2

aliases:
  - &restore-cache-src
    key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

  - &save-cache-src
    key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &restore-cache-starters
    keys:
      - angular-official-blank-dependency-cache-{{ .Branch }}{{ checksum "package.json" }}

  - &save-cache-angular-official-blank
    key: angular-official-blank-dependency-cache-{{ .Branch }}{{ checksum "package.json" }}
    paths:
      - build/angular-official-blank/node_modules

defaults: &defaults
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache: *restore-cache-src
      - run: npm install
      - save_cache: *save-cache-src
      - run: npm run src:lint
      - run: npm run src:build
      - run: npm run starters:build
  test:
    <<: *defaults
    steps:
      - restore_cache: *restore-cache-starters
      - run: npm run starters:test
      - save_cache: *save-cache-angular-official-blank
  deploy:
    <<: *defaults
    steps:
      - run: npm run starters:deploy -- --tag latest

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires: [build]
      - deploy:
          requires: [test]
          filters:
            branches:
              only: master
