version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run src:lint
      - run: npm run src:build
      - run: npm run starters:build
      - restore_cache:
          key: angular-official-blank-dependency-cache-{{ checksum "package.json" }}
      - run: npm run starters:test
      - save_cache:
          key: angular-official-blank-dependency-cache-{{ checksum "package.json" }}
          paths:
            - build/angular-official-blank/node_modules
      - run: npm run starters:deploy -- --tag latest
    branches:
      only:
        - master
