version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run tsc
      - run: npm run build
      - run: npm run deploy -- --tag latest
    branches:
      only:
        - master
